api=../api
tags=../ref/Tags
guide=../../guide
github=https://github.com/graceframework/grace-data-examples
gormapi=https://graceframework.org/grace-data/2024.0.x/api
sourcedir=.
sourceRepo=https://github.com/graceframework/grace-data-examples/edit/2024.0.x/src/docs
safe=UNSAFE
title=Grace Data Examples
subtitle=Example projects for the different Grace Data modules to showcase the API and how to use the features provided by the modules.
authors=Michael Yan
copyright=Copyright &copy; 2022-2025 Michael Yan and the original authors. The content is licensed under a Creative Commons Attribution 4.0 International (CC BY SA 4.0) license.
